[package]
name = "loci"
version = "0.1.1"
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.11", package = "gtk4", features = ["gnome_48"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
ashpd = { version = "0.13", default-features = false, features = ["tokio", "location"] }
ferrostar = { version = "0.49", default-features = false, features = ["std"] }
geo = "0.31"
futures-util = { version = "0.3.32", default-features = false, features = ["std"] }

[dependencies.adw]
package = "libadwaita"
version = "0.9"
features = ["v1_7"]

[dependencies.shumate]
package = "libshumate"
version = "0.8"

[profile.release]
strip = true
lto = true
opt-level = "s"
